dist:     trusty    
sudo:     required  

language: cpp       
                   
os:
    - linux

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release

install:
    # скрипт настройки среды и установки зависимостей:
    - source CI/travis/install-linux.sh

script:
    # скрипт сборки и тестирования проекта:
    - mkdir build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU
    - cmake --build .

deploy:
    provider:     releases
    
    file:         
    - file1.pkg
    
    skip_cleanup: true

    on:
        tags:     true
