image: Visual Studio 2017

init:
    - git config --global core.autocrlf input

shallow_clone: true              

matrix:
    fast_finish: false           

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc15
        - TOOLCHAIN: msvc17



build_script:
    - mkdir build
    - cd build



artifacts:
    - path: <local-package-path>
      name: package_name



    auth_token:
        secure: <encrypted-github-token>

    artifact: package_name
    force_update: true

    on:
        appveyor_repo_tag: true
