image: Visual Studio 2017

init:
    - git config --global core.autocrlf input

clone_folder: E:\projects
shallow_clone: true              

matrix:
    fast_finish: false           

platform:
    - x64

configuration:
    - Debug
    - Release

environment:
    matrix:
        - TOOLCHAIN: msvc12
        - TOOLCHAIN: msvc15
        - TOOLCHAIN: msvc17

install:
    - call ci\appveyor\set-env.bat %TOOLCHAIN% %PLATFORM%

    - appveyor DownloadFile <url> -FileName <local-file>
    - 7z e -y <local-file> -o<local-dir>
    - ...

build_script:
    - mkdir build
    - cd build
    - cmake .. %CMAKE_CONFIGURE_FLAGS%
    - cmake --build . %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure

artifacts:
    - path: <local-package-path>
      name: package_name

deploy:
    description: '$(APPVEYOR_REPO_TAG_NAME)'
    provider: GitHub

    auth_token:
        secure: <encrypted-github-token>

    artifact: package_name
    force_update: true

    on:
        appveyor_repo_tag: true
